import React, { useState, useEffect } from 'react';
import {
  User,
  Mail,
  Phone,
  BookOpen,
  GraduationCap,
  Calendar,
  MapPin,
  Image as ImageIcon,
  Save,
  ArrowLeft,
  Info,
  Check,
  AlertCircle,
  Layers,
  ShieldCheck
} from 'lucide-react';
import {
  Teacher,
  TeacherFormData,
  SUBJECT_OPTIONS,
  SECTION_OPTIONS
} from '../../../types/teacher';
import { CLASS_OPTIONS } from '../../../types/student';
import { teacherService } from '../../../services/teacherService';

interface TeacherFormProps {
  initialTeacher?: Teacher | null;
  onSubmit: (data: TeacherFormData) => Promise<void>;
  onCancel: () => void;
  isEditing?: boolean;
}

export default function TeacherForm({
  initialTeacher,
  onSubmit,
  onCancel,
  isEditing = false,
}: TeacherFormProps) {
  const [formData, setFormData] = useState<TeacherFormData>({
    teacherId: initialTeacher?.teacherId || '',
    name: initialTeacher?.name || '',
    email: initialTeacher?.email || '',
    phone: initialTeacher?.phone || '',
    alternatePhone: initialTeacher?.alternatePhone || '',
    subjects: initialTeacher?.subjects || [],
    assignedClasses: initialTeacher?.assignedClasses || [],
    assignedSections: initialTeacher?.assignedSections || ['A'],
    qualification: initialTeacher?.qualification || '',
    address: initialTeacher?.address || '',
    joiningDate: initialTeacher?.joiningDate || new Date().toISOString().split('T')[0],
    profilePhoto: initialTeacher?.profilePhoto || '',
    status: initialTeacher?.status || 'ACTIVE',
  });

  const [autoGeneratedId, setAutoGeneratedId] = useState<string>('');
  const [customSubjectInput, setCustomSubjectInput] = useState<string>('');
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState<boolean>(false);
  const [idChecking, setIdChecking] = useState<boolean>(false);

  // Fetch auto-generated teacher ID if creating new teacher
  useEffect(() => {
    if (!isEditing) {
      teacherService.generateNextTeacherId().then((genId) => {
        setAutoGeneratedId(genId);
        if (!formData.teacherId) {
          setFormData((prev) => ({ ...prev, teacherId: genId }));
        }
      });
    }
  }, [isEditing]);

  // Handle subject toggle
  const toggleSubject = (subjectName: string) => {
    setFormData((prev) => {
      const exists = prev.subjects.includes(subjectName);
      const updated = exists
        ? prev.subjects.filter((s) => s !== subjectName)
        : [...prev.subjects, subjectName];
      return { ...prev, subjects: updated };
    });
    if (errors.subjects) {
      setErrors((prev) => ({ ...prev, subjects: '' }));
    }
  };

  // Add custom subject
  const handleAddCustomSubject = (e: React.KeyboardEvent | React.MouseEvent) => {
    if ('key' in e && e.key !== 'Enter') return;
    e.preventDefault();
    const trimmed = customSubjectInput.trim();
    if (trimmed && !formData.subjects.includes(trimmed)) {
      setFormData((prev) => ({
        ...prev,
        subjects: [...prev.subjects, trimmed],
      }));
      setCustomSubjectInput('');
      if (errors.subjects) {
        setErrors((prev) => ({ ...prev, subjects: '' }));
      }
    }
  };

  // Handle class toggle
  const toggleClass = (className: string) => {
    setFormData((prev) => {
      const exists = prev.assignedClasses.includes(className);
      const updated = exists
        ? prev.assignedClasses.filter((c) => c !== className)
        : [...prev.assignedClasses, className];
      return { ...prev, assignedClasses: updated };
    });
    if (errors.assignedClasses) {
      setErrors((prev) => ({ ...prev, assignedClasses: '' }));
    }
  };

  // Handle section toggle
  const toggleSection = (section: string) => {
    setFormData((prev) => {
      const current = prev.assignedSections || [];
      const exists = current.includes(section);
      const updated = exists
        ? current.filter((s) => s !== section)
        : [...current, section];
      return { ...prev, assignedSections: updated };
    });
  };

  // Validation
  const validateForm = async (): Promise<boolean> => {
    const newErrors: Record<string, string> = {};

    // Teacher Name
    if (!formData.name.trim()) {
      newErrors.name = 'Teacher Name is required';
    } else if (formData.name.trim().length < 2) {
      newErrors.name = 'Teacher Name must be at least 2 characters';
    }

    // Email
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!formData.email.trim()) {
      newErrors.email = 'Email address is required';
    } else if (!emailRegex.test(formData.email.trim())) {
      newErrors.email = 'Please enter a valid email address';
    }

    // Phone (Valid 10-digit Indian number)
    const phoneClean = formData.phone.trim();
    const indianPhoneRegex = /^[6-9]\d{9}$/;
    if (!phoneClean) {
      newErrors.phone = 'Mobile Number is required';
    } else if (!indianPhoneRegex.test(phoneClean)) {
      newErrors.phone = 'Enter a valid 10-digit Indian mobile number (starts with 6-9)';
    }

    // Alternate phone validation if provided
    if (formData.alternatePhone.trim()) {
      if (!indianPhoneRegex.test(formData.alternatePhone.trim())) {
        newErrors.alternatePhone = 'Alternate Phone must be a valid 10-digit mobile number';
      }
    }

    // Subjects: At least one required
    if (formData.subjects.length === 0) {
      newErrors.subjects = 'Please select at least one subject';
    }

    // Assigned Classes: At least one required
    if (formData.assignedClasses.length === 0) {
      newErrors.assignedClasses = 'Please select at least one assigned class';
    }

    // Check custom Teacher ID duplicate if changed
    if (!isEditing && formData.teacherId) {
      setIdChecking(true);
      const exists = await teacherService.checkTeacherIdExists(
        formData.teacherId,
        initialTeacher?.uid
      );
      setIdChecking(false);
      if (exists) {
        newErrors.teacherId = `Teacher ID '${formData.teacherId}' is already in use`;
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const isValid = await validateForm();
    if (!isValid) return;

    setSubmitting(true);
    try {
      await onSubmit(formData);
    } catch (err: any) {
      console.error('Error submitting teacher form:', err);
      setErrors((prev) => ({
        ...prev,
        form: err.message || 'Failed to save teacher details. Please try again.',
      }));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Top Header */}
      <div className="flex items-center justify-between pb-4 border-b border-gray-200">
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={onCancel}
            className="p-2 text-gray-500 hover:text-gray-800 hover:bg-gray-100 rounded-xl transition-colors cursor-pointer"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <h1 className="text-xl font-black text-gray-900 tracking-tight">
              {isEditing ? 'Edit Teacher Information' : 'Add New Teacher'}
            </h1>
            <p className="text-xs text-gray-500">
              {isEditing
                ? 'Update profile and academic details for this teacher'
                : 'Register a new faculty member at GP Academy'}
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={onCancel}
          className="px-4 py-2 border border-gray-200 rounded-xl text-xs font-extrabold text-gray-700 hover:bg-gray-50 transition-colors cursor-pointer"
        >
          Cancel
        </button>
      </div>

      {/* Backend Account Setup Info Notice */}
      <div className="p-4 bg-emerald-50/90 border border-emerald-200/80 rounded-2xl flex items-start gap-3">
        <ShieldCheck className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
        <div className="text-xs text-emerald-950 leading-relaxed">
          <span className="font-extrabold block text-emerald-950 mb-0.5">
            Secure Authentication & Password Setup Flow
          </span>
          When created, a secure Firebase Authentication account with role <code className="px-1 py-0.5 bg-emerald-100 text-emerald-900 rounded font-mono font-bold">TEACHER</code> is automatically provisioned. An official password setup link is dispatched to the teacher's registered email address. Passwords are never visible to admins, stored in plaintext, or recorded in logs.
        </div>
      </div>

      {/* Global Form Error */}
      {errors.form && (
        <div className="p-4 bg-rose-50 border border-rose-200 rounded-2xl text-rose-800 text-xs font-medium flex items-center gap-2">
          <AlertCircle className="w-4 h-4 text-rose-600 shrink-0" />
          <span>{errors.form}</span>
        </div>
      )}

      {/* Form Container */}
      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Section 1: Basic & Contact Info */}
        <div className="bg-white rounded-2xl border border-gray-200/90 p-5 shadow-2xs space-y-4">
          <div className="flex items-center justify-between border-b border-gray-100 pb-2">
            <h2 className="text-xs font-black uppercase tracking-wider text-[#001c46]">
              Personal & Contact Information
            </h2>
            {/* Status Selector */}
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold text-gray-600">Account Status:</span>
              <div className="inline-flex rounded-lg p-0.5 bg-gray-100 border border-gray-200">
                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, status: 'ACTIVE' })}
                  className={`px-3 py-1 rounded-md text-xs font-black transition-all cursor-pointer ${
                    formData.status !== 'DISABLED'
                      ? 'bg-emerald-600 text-white shadow-2xs'
                      : 'text-gray-600 hover:text-gray-900'
                  }`}
                >
                  ACTIVE
                </button>
                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, status: 'DISABLED' })}
                  className={`px-3 py-1 rounded-md text-xs font-black transition-all cursor-pointer ${
                    formData.status === 'DISABLED'
                      ? 'bg-rose-600 text-white shadow-2xs'
                      : 'text-gray-600 hover:text-gray-900'
                  }`}
                >
                  DISABLED
                </button>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Teacher ID */}
            <div>
              <label className="block text-xs font-extrabold text-gray-700 mb-1">
                Teacher ID {isEditing ? '(Read Only)' : '(Auto-generated)'}
              </label>
              <input
                type="text"
                disabled={isEditing}
                value={formData.teacherId}
                onChange={(e) => {
                  setFormData({ ...formData, teacherId: e.target.value });
                  if (errors.teacherId) setErrors({ ...errors, teacherId: '' });
                }}
                placeholder={autoGeneratedId || 'e.g. GP-T-2026-001'}
                className={`w-full px-3.5 py-2.5 bg-gray-50 border rounded-xl text-xs font-mono font-bold text-gray-800 focus:outline-none transition-all ${
                  isEditing ? 'bg-gray-100 text-gray-500 cursor-not-allowed border-gray-200' : 'focus:bg-white border-gray-200 focus:border-[#001c46]'
                } ${errors.teacherId ? 'border-rose-500' : ''}`}
              />
              {errors.teacherId && (
                <p className="text-[11px] text-rose-600 font-bold mt-1">{errors.teacherId}</p>
              )}
              {!isEditing && (
                <p className="text-[10px] text-gray-400 mt-1">
                  Format: GP-T-2026-001. You can leave as auto-generated or specify a custom ID.
                </p>
              )}
            </div>

            {/* Teacher Name */}
            <div>
              <label className="block text-xs font-extrabold text-gray-700 mb-1">
                Teacher Full Name <span className="text-rose-500">*</span>
              </label>
              <div className="relative">
                <User className="w-4 h-4 absolute left-3 top-3 text-gray-400" />
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => {
                    setFormData({ ...formData, name: e.target.value });
                    if (errors.name) setErrors({ ...errors, name: '' });
                  }}
                  placeholder="e.g. Dr. Rajesh Sharma"
                  className={`w-full pl-9 pr-3.5 py-2.5 bg-gray-50 hover:bg-gray-100/80 focus:bg-white border rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all ${
                    errors.name ? 'border-rose-500' : 'border-gray-200 focus:border-[#001c46]'
                  }`}
                />
              </div>
              {errors.name && (
                <p className="text-[11px] text-rose-600 font-bold mt-1">{errors.name}</p>
              )}
            </div>

            {/* Email */}
            <div>
              <label className="block text-xs font-extrabold text-gray-700 mb-1">
                Email Address <span className="text-rose-500">*</span>
              </label>
              <div className="relative">
                <Mail className="w-4 h-4 absolute left-3 top-3 text-gray-400" />
                <input
                  type="email"
                  value={formData.email}
                  onChange={(e) => {
                    setFormData({ ...formData, email: e.target.value });
                    if (errors.email) setErrors({ ...errors, email: '' });
                  }}
                  placeholder="e.g. rajesh.sharma@gpacademy.edu.in"
                  className={`w-full pl-9 pr-3.5 py-2.5 bg-gray-50 hover:bg-gray-100/80 focus:bg-white border rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all ${
                    errors.email ? 'border-rose-500' : 'border-gray-200 focus:border-[#001c46]'
                  }`}
                />
              </div>
              {errors.email && (
                <p className="text-[11px] text-rose-600 font-bold mt-1">{errors.email}</p>
              )}
            </div>

            {/* Mobile Number */}
            <div>
              <label className="block text-xs font-extrabold text-gray-700 mb-1">
                Mobile Number <span className="text-rose-500">*</span>
              </label>
              <div className="relative">
                <Phone className="w-4 h-4 absolute left-3 top-3 text-gray-400" />
                <input
                  type="tel"
                  maxLength={10}
                  value={formData.phone}
                  onChange={(e) => {
                    const digits = e.target.value.replace(/\D/g, '');
                    setFormData({ ...formData, phone: digits });
                    if (errors.phone) setErrors({ ...errors, phone: '' });
                  }}
                  placeholder="10-digit mobile number"
                  className={`w-full pl-9 pr-3.5 py-2.5 bg-gray-50 hover:bg-gray-100/80 focus:bg-white border rounded-xl text-xs font-mono font-bold text-gray-900 focus:outline-none transition-all ${
                    errors.phone ? 'border-rose-500' : 'border-gray-200 focus:border-[#001c46]'
                  }`}
                />
              </div>
              {errors.phone && (
                <p className="text-[11px] text-rose-600 font-bold mt-1">{errors.phone}</p>
              )}
            </div>

            {/* Alternate Phone */}
            <div>
              <label className="block text-xs font-extrabold text-gray-700 mb-1">
                Alternate Phone <span className="text-gray-400 font-normal">(Optional)</span>
              </label>
              <div className="relative">
                <Phone className="w-4 h-4 absolute left-3 top-3 text-gray-400" />
                <input
                  type="tel"
                  maxLength={10}
                  value={formData.alternatePhone}
                  onChange={(e) => {
                    const digits = e.target.value.replace(/\D/g, '');
                    setFormData({ ...formData, alternatePhone: digits });
                    if (errors.alternatePhone) setErrors({ ...errors, alternatePhone: '' });
                  }}
                  placeholder="Optional 10-digit contact"
                  className={`w-full pl-9 pr-3.5 py-2.5 bg-gray-50 hover:bg-gray-100/80 focus:bg-white border rounded-xl text-xs font-mono font-bold text-gray-900 focus:outline-none transition-all ${
                    errors.alternatePhone ? 'border-rose-500' : 'border-gray-200 focus:border-[#001c46]'
                  }`}
                />
              </div>
              {errors.alternatePhone && (
                <p className="text-[11px] text-rose-600 font-bold mt-1">{errors.alternatePhone}</p>
              )}
            </div>

            {/* Joining Date */}
            <div>
              <label className="block text-xs font-extrabold text-gray-700 mb-1">
                Joining Date <span className="text-gray-400 font-normal">(Optional)</span>
              </label>
              <div className="relative">
                <Calendar className="w-4 h-4 absolute left-3 top-3 text-gray-400" />
                <input
                  type="date"
                  value={formData.joiningDate}
                  onChange={(e) => setFormData({ ...formData, joiningDate: e.target.value })}
                  className="w-full pl-9 pr-3.5 py-2.5 bg-gray-50 hover:bg-gray-100/80 focus:bg-white border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all"
                />
              </div>
            </div>
          </div>

          {/* Qualification & Address */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
            {/* Qualification */}
            <div>
              <label className="block text-xs font-extrabold text-gray-700 mb-1">
                Qualification <span className="text-gray-400 font-normal">(Optional)</span>
              </label>
              <div className="relative">
                <GraduationCap className="w-4 h-4 absolute left-3 top-3 text-gray-400" />
                <input
                  type="text"
                  value={formData.qualification}
                  onChange={(e) => setFormData({ ...formData, qualification: e.target.value })}
                  placeholder="e.g. M.Sc. Physics, B.Ed"
                  className="w-full pl-9 pr-3.5 py-2.5 bg-gray-50 hover:bg-gray-100/80 focus:bg-white border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all"
                />
              </div>
            </div>

            {/* Profile Photo URL */}
            <div>
              <label className="block text-xs font-extrabold text-gray-700 mb-1">
                Profile Photo URL <span className="text-gray-400 font-normal">(Optional)</span>
              </label>
              <div className="relative">
                <ImageIcon className="w-4 h-4 absolute left-3 top-3 text-gray-400" />
                <input
                  type="url"
                  value={formData.profilePhoto}
                  onChange={(e) => setFormData({ ...formData, profilePhoto: e.target.value })}
                  placeholder="https://example.com/photo.jpg"
                  className="w-full pl-9 pr-3.5 py-2.5 bg-gray-50 hover:bg-gray-100/80 focus:bg-white border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all"
                />
              </div>
            </div>
          </div>

          {/* Residential Address */}
          <div>
            <label className="block text-xs font-extrabold text-gray-700 mb-1">
              Residential Address <span className="text-gray-400 font-normal">(Optional)</span>
            </label>
            <div className="relative">
              <MapPin className="w-4 h-4 absolute left-3 top-3 text-gray-400" />
              <textarea
                rows={2}
                value={formData.address}
                onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                placeholder="Complete street address, city, state, pincode"
                className="w-full pl-9 pr-3.5 py-2 bg-gray-50 hover:bg-gray-100/80 focus:bg-white border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all"
              />
            </div>
          </div>
        </div>

        {/* Section 2: Subjects Selection */}
        <div className="bg-white rounded-2xl border border-gray-200/90 p-5 shadow-2xs space-y-3">
          <div className="flex items-center justify-between border-b border-gray-100 pb-2">
            <div className="flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-[#001c46]" />
              <h2 className="text-xs font-black uppercase tracking-wider text-[#001c46]">
                Subjects Taught <span className="text-rose-500">*</span>
              </h2>
            </div>
            <span className="text-[10px] font-extrabold text-gray-500">
              Selected: {formData.subjects.length}
            </span>
          </div>

          {errors.subjects && (
            <p className="text-[11px] text-rose-600 font-bold">{errors.subjects}</p>
          )}

          {/* Predefined subjects grid */}
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2 pt-1">
            {SUBJECT_OPTIONS.map((subject) => {
              const isSelected = formData.subjects.includes(subject);
              return (
                <button
                  key={subject}
                  type="button"
                  onClick={() => toggleSubject(subject)}
                  className={`flex items-center justify-between px-3 py-2 rounded-xl text-xs font-bold transition-all text-left border cursor-pointer ${
                    isSelected
                      ? 'bg-amber-50 text-amber-900 border-amber-300 shadow-2xs'
                      : 'bg-gray-50/80 text-gray-700 border-gray-200 hover:bg-gray-100'
                  }`}
                >
                  <span className="truncate">{subject}</span>
                  {isSelected && <Check className="w-3.5 h-3.5 text-amber-600 shrink-0 ml-1" />}
                </button>
              );
            })}
          </div>

          {/* Add custom subject */}
          <div className="pt-2">
            <label className="block text-[11px] font-extrabold text-gray-500 mb-1">
              Add Other Subject (if not listed above)
            </label>
            <div className="flex gap-2">
              <input
                type="text"
                value={customSubjectInput}
                onChange={(e) => setCustomSubjectInput(e.target.value)}
                onKeyDown={handleAddCustomSubject}
                placeholder="Type custom subject name and press Enter"
                className="flex-1 px-3.5 py-2 bg-gray-50 hover:bg-gray-100/80 focus:bg-white border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all"
              />
              <button
                type="button"
                onClick={handleAddCustomSubject}
                className="px-4 py-2 bg-[#001c46] hover:bg-[#001c46]/90 text-white font-extrabold text-xs rounded-xl transition-colors cursor-pointer"
              >
                Add Subject
              </button>
            </div>
          </div>
        </div>

        {/* Section 3: Assigned Classes Selection */}
        <div className="bg-white rounded-2xl border border-gray-200/90 p-5 shadow-2xs space-y-3">
          <div className="flex items-center justify-between border-b border-gray-100 pb-2">
            <div className="flex items-center gap-2">
              <User className="w-4 h-4 text-[#001c46]" />
              <h2 className="text-xs font-black uppercase tracking-wider text-[#001c46]">
                Assigned Classes <span className="text-rose-500">*</span>
              </h2>
            </div>
            <span className="text-[10px] font-extrabold text-gray-500">
              Selected: {formData.assignedClasses.length}
            </span>
          </div>

          {errors.assignedClasses && (
            <p className="text-[11px] text-rose-600 font-bold">{errors.assignedClasses}</p>
          )}

          {/* Classes grid */}
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2 pt-1">
            {CLASS_OPTIONS.map((cls) => {
              const isSelected = formData.assignedClasses.includes(cls);
              return (
                <button
                  key={cls}
                  type="button"
                  onClick={() => toggleClass(cls)}
                  className={`flex items-center justify-between px-3 py-2 rounded-xl text-xs font-bold transition-all text-left border cursor-pointer ${
                    isSelected
                      ? 'bg-blue-50 text-blue-900 border-blue-300 shadow-2xs'
                      : 'bg-gray-50/80 text-gray-700 border-gray-200 hover:bg-gray-100'
                  }`}
                >
                  <span className="truncate">{cls}</span>
                  {isSelected && <Check className="w-3.5 h-3.5 text-blue-600 shrink-0 ml-1" />}
                </button>
              );
            })}
          </div>

          {/* Sections Allocation */}
          <div className="pt-3 border-t border-gray-100">
            <div className="flex items-center gap-2 mb-2">
              <Layers className="w-4 h-4 text-[#001c46]" />
              <label className="text-xs font-black text-[#001c46] uppercase tracking-wider">
                Assigned Section(s)
              </label>
              <span className="text-[10px] text-gray-500">(Applicable to assigned classes)</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {SECTION_OPTIONS.map((sec) => {
                const isSelected = (formData.assignedSections || []).includes(sec);
                return (
                  <button
                    key={sec}
                    type="button"
                    onClick={() => toggleSection(sec)}
                    className={`px-4 py-2 rounded-xl text-xs font-extrabold transition-all border cursor-pointer flex items-center gap-2 ${
                      isSelected
                        ? 'bg-[#001c46] text-white border-[#001c46] shadow-2xs'
                        : 'bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100'
                    }`}
                  >
                    <span>Section {sec}</span>
                    {isSelected && <Check className="w-3.5 h-3.5 text-amber-400" />}
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        {/* Form Actions */}
        <div className="flex items-center justify-end gap-3 pt-4 border-t border-gray-200">
          <button
            type="button"
            onClick={onCancel}
            disabled={submitting}
            className="px-5 py-2.5 border border-gray-200 hover:bg-gray-50 rounded-xl text-xs font-extrabold text-gray-700 transition-colors cursor-pointer"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={submitting || idChecking}
            className="px-6 py-2.5 bg-[#001c46] hover:bg-[#001c46]/90 text-white rounded-xl text-xs font-extrabold shadow-md transition-all cursor-pointer flex items-center gap-2"
          >
            {submitting ? (
              <>
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                <span>Provisioning Account...</span>
              </>
            ) : (
              <>
                <Save className="w-4 h-4" />
                <span>{isEditing ? 'Update Teacher' : 'Create Teacher & Send Setup Email'}</span>
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
}
