import React, { useState, useEffect, useMemo } from 'react';
import {
  User,
  BookOpen,
  Save,
  ArrowLeft,
  Info,
  AlertCircle
} from 'lucide-react';
import {
  Student,
  StudentFormData,
  CLASS_OPTIONS,
  getAllowedBoardsForClass,
  formatStudentId
} from '../../../types/student';

interface StudentFormProps {
  initialData?: Student | null;
  autoGeneratedStudentId?: string;
  isEditMode?: boolean;
  isLoading?: boolean;
  onSubmit: (data: StudentFormData) => Promise<void>;
  onCancel: () => void;
}

export default function StudentForm({
  initialData,
  autoGeneratedStudentId = '1GP001',
  isEditMode = false,
  isLoading = false,
  onSubmit,
  onCancel,
}: StudentFormProps) {
  const [formData, setFormData] = useState<StudentFormData>({
    name: initialData?.name || '',
    email: initialData?.email || '',
    className: initialData?.className || 'Class 1',
    section: initialData?.section || 'A',
    rollNumber: initialData?.rollNumber || '',
    board: initialData?.board || 'CBSE',
    parentName: initialData?.parentName || '',
    phone: initialData?.phone || '',
    alternatePhone: initialData?.alternatePhone || '',
    dateOfBirth: initialData?.dateOfBirth || '',
    address: initialData?.address || '',
    previousSchool: initialData?.previousSchool || '',
    admissionDate: initialData?.admissionDate || new Date().toISOString().split('T')[0],
    profilePhoto: initialData?.profilePhoto || '',
  });

  // Calculate dynamic Student ID based on [ClassDigit]GP[3-digit Roll] format
  const displayedStudentId = useMemo(() => {
    if (isEditMode && initialData?.studentId) {
      const cleanRoll = formData.rollNumber.trim();
      if (cleanRoll) {
        const parsed = parseInt(cleanRoll.replace(/\D/g, ''), 10);
        if (!isNaN(parsed) && parsed > 0) {
          return formatStudentId(formData.className, parsed);
        }
      }
      return initialData.studentId;
    }
    const cleanRoll = formData.rollNumber.trim();
    if (cleanRoll) {
      const parsed = parseInt(cleanRoll.replace(/\D/g, ''), 10);
      if (!isNaN(parsed) && parsed > 0) {
        return formatStudentId(formData.className, parsed);
      }
    }
    return autoGeneratedStudentId || formatStudentId(formData.className, 1);
  }, [isEditMode, initialData, formData.className, formData.rollNumber, autoGeneratedStudentId]);

  const [errors, setErrors] = useState<Record<string, string>>({});

  // Compute allowed boards when class changes
  const allowedBoards = getAllowedBoardsForClass(formData.className);

  // Automatically sync board if chosen board is not allowed in new class
  useEffect(() => {
    if (!allowedBoards.includes(formData.board)) {
      setFormData((prev) => ({ ...prev, board: allowedBoards[0] }));
    }
  }, [formData.className, allowedBoards]);

  // Handle class change
  const handleClassChange = (newClass: string) => {
    const newAllowed = getAllowedBoardsForClass(newClass);
    setFormData((prev) => ({
      ...prev,
      className: newClass,
      board: newAllowed.includes(prev.board) ? prev.board : newAllowed[0],
    }));
    if (errors.className) setErrors((prev) => ({ ...prev, className: '' }));
  };

  // Validate form
  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};

    // Name required
    if (!formData.name.trim()) {
      newErrors.name = 'Student name is required';
    }

    // Parent name required
    if (!formData.parentName.trim()) {
      newErrors.parentName = 'Parent / Guardian name is required';
    }

    // Phone required and 10 digits validation
    const cleanPhone = formData.phone.trim();
    if (!cleanPhone) {
      newErrors.phone = 'Primary mobile number is required';
    } else if (!/^[6-9]\d{9}$/.test(cleanPhone) && !/^\d{10}$/.test(cleanPhone)) {
      newErrors.phone = 'Please enter a valid 10-digit mobile number';
    }

    // Class required
    if (!formData.className) {
      newErrors.className = 'Admission class is required';
    }

    // Board required
    if (!formData.board) {
      newErrors.board = 'Board selection is required';
    }

    // Email format validation if provided
    if (formData.email.trim() && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email.trim())) {
      newErrors.email = 'Please enter a valid email address';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validate()) return;
    await onSubmit(formData);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 font-sans">
      {/* Top Header Card */}
      <div className="bg-white p-6 rounded-3xl border border-gray-200/80 shadow-xs flex items-center justify-between gap-4">
        <div className="flex items-center gap-3.5">
          <button
            onClick={onCancel}
            className="p-2 text-gray-500 hover:text-[#001c46] hover:bg-gray-100 rounded-xl transition-colors cursor-pointer"
            title="Back to Students"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>

          <div>
            <span className="text-[10px] font-extrabold text-[#001c46] bg-[#FFC907] px-2 py-0.5 rounded uppercase tracking-wider inline-block">
              {isEditMode ? 'Edit Record' : 'New Enrollment'}
            </span>
            <h2 className="text-xl font-black text-[#001c46] tracking-tight mt-0.5">
              {isEditMode ? `Edit Student Profile (${initialData?.studentId})` : 'Add New Student'}
            </h2>
          </div>
        </div>

        {/* Auto Generated ID badge */}
        <div className="text-right hidden sm:block">
          <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
            Student ID ([Class]GP[Roll])
          </span>
          <span className="text-base font-mono font-black text-[#001c46] bg-blue-50 px-3 py-1 rounded-xl border border-blue-100 inline-block">
            {displayedStudentId}
          </span>
        </div>
      </div>

      {/* Account Setup Notice */}
      <div className="bg-blue-50/80 border border-blue-200/80 p-4 rounded-2xl flex items-start gap-3 text-xs text-blue-900">
        <Info className="w-5 h-5 text-blue-700 shrink-0 mt-0.5" />
        <div className="space-y-0.5">
          <p className="font-bold">Student Account Notice:</p>
          <p className="text-blue-800 leading-relaxed">
            Student profile will be saved securely in the Firestore database. Student login account will be created after secure account setup via Cloud Functions / Admin SDK.
          </p>
        </div>
      </div>

      {/* Form Container */}
      <form onSubmit={handleSubmit} className="bg-white p-6 sm:p-8 rounded-3xl border border-gray-200/80 shadow-xs space-y-8">
        
        {/* Section 1: Basic & Required Information */}
        <div className="space-y-4">
          <div className="border-b border-gray-100 pb-3 flex items-center gap-2 text-[#001c46]">
            <User className="w-4 h-4 text-[#FFC907]" />
            <h3 className="text-sm font-black uppercase tracking-wider">Required Student Information</h3>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
            {/* Student Name */}
            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1.5">
                Student Full Name <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                value={formData.name}
                onChange={(e) => {
                  setFormData({ ...formData, name: e.target.value });
                  if (errors.name) setErrors({ ...errors, name: '' });
                }}
                placeholder="e.g. Aarav Sharma"
                className={`w-full px-4 py-2.5 bg-gray-50 border ${
                  errors.name ? 'border-red-500 focus:ring-red-200' : 'border-gray-200 focus:border-[#001c46]'
                } rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all`}
              />
              {errors.name && (
                <p className="text-[11px] font-bold text-red-500 mt-1 flex items-center gap-1">
                  <AlertCircle className="w-3 h-3" /> {errors.name}
                </p>
              )}
            </div>

            {/* Parent Name */}
            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1.5">
                Parent / Guardian Name <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                value={formData.parentName}
                onChange={(e) => {
                  setFormData({ ...formData, parentName: e.target.value });
                  if (errors.parentName) setErrors({ ...errors, parentName: '' });
                }}
                placeholder="e.g. Rajesh Sharma"
                className={`w-full px-4 py-2.5 bg-gray-50 border ${
                  errors.parentName ? 'border-red-500 focus:ring-red-200' : 'border-gray-200 focus:border-[#001c46]'
                } rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all`}
              />
              {errors.parentName && (
                <p className="text-[11px] font-bold text-red-500 mt-1 flex items-center gap-1">
                  <AlertCircle className="w-3 h-3" /> {errors.parentName}
                </p>
              )}
            </div>

            {/* Mobile Number */}
            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1.5">
                Primary Mobile Number <span className="text-red-500">*</span>
              </label>
              <div className="relative">
                <span className="absolute left-3.5 top-2.5 text-xs font-extrabold text-gray-400">+91</span>
                <input
                  type="tel"
                  maxLength={10}
                  value={formData.phone}
                  onChange={(e) => {
                    const clean = e.target.value.replace(/\D/g, '');
                    setFormData({ ...formData, phone: clean });
                    if (errors.phone) setErrors({ ...errors, phone: '' });
                  }}
                  placeholder="9876543210"
                  className={`w-full pl-12 pr-4 py-2.5 bg-gray-50 font-mono border ${
                    errors.phone ? 'border-red-500 focus:ring-red-200' : 'border-gray-200 focus:border-[#001c46]'
                  } rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all`}
                />
              </div>
              {errors.phone && (
                <p className="text-[11px] font-bold text-red-500 mt-1 flex items-center gap-1">
                  <AlertCircle className="w-3 h-3" /> {errors.phone}
                </p>
              )}
            </div>

            {/* Admission Class */}
            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1.5">
                Admission Class <span className="text-red-500">*</span>
              </label>
              <select
                value={formData.className}
                onChange={(e) => handleClassChange(e.target.value)}
                className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all cursor-pointer"
              >
                {CLASS_OPTIONS.map((cls) => (
                  <option key={cls} value={cls}>
                    {cls}
                  </option>
                ))}
              </select>
            </div>

            {/* Board Selection */}
            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1.5">
                Academic Board <span className="text-red-500">*</span>
              </label>
              <select
                value={formData.board}
                onChange={(e) => {
                  setFormData({ ...formData, board: e.target.value as any });
                  if (errors.board) setErrors({ ...errors, board: '' });
                }}
                className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all cursor-pointer"
              >
                {allowedBoards.map((b) => (
                  <option key={b} value={b}>
                    {b}
                  </option>
                ))}
              </select>
              {allowedBoards.length === 1 && (
                <p className="text-[10px] text-gray-500 mt-1 italic">
                  Note: Nursery to Class 8 follows CBSE curriculum exclusively.
                </p>
              )}
              {formData.className === 'Class 9' && (
                <p className="text-[10px] text-blue-600 mt-1 font-bold">
                  Class 9: Please select applicable board (CBSE or UP Board).
                </p>
              )}
            </div>

            {/* Section & Roll Number */}
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-bold text-gray-700 mb-1.5">Section</label>
                <input
                  type="text"
                  maxLength={5}
                  value={formData.section}
                  onChange={(e) => setFormData({ ...formData, section: e.target.value.toUpperCase() })}
                  placeholder="A"
                  className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all uppercase"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-700 mb-1.5">
                  Roll No
                  <span className="text-[10px] text-blue-600 font-semibold ml-1.5">(Format: e.g. 14 in Class 10 → 10GP014)</span>
                </label>
                <input
                  type="text"
                  maxLength={10}
                  value={formData.rollNumber}
                  onChange={(e) => setFormData({ ...formData, rollNumber: e.target.value })}
                  placeholder="e.g. 15"
                  className="w-full px-4 py-2.5 bg-gray-50 font-mono border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-bold text-gray-900 focus:outline-none transition-all"
                />
              </div>
            </div>
          </div>
        </div>

        {/* Section 2: Optional Contact & Personal Information */}
        <div className="space-y-4 pt-4 border-t border-gray-100">
          <div className="pb-2 flex items-center gap-2 text-[#001c46]">
            <BookOpen className="w-4 h-4 text-[#FFC907]" />
            <h3 className="text-sm font-black uppercase tracking-wider">Additional Student Details (Optional)</h3>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
            {/* Email */}
            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1.5">Student Email</label>
              <input
                type="email"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                placeholder="student@example.com"
                className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-medium text-gray-900 focus:outline-none transition-all"
              />
              {errors.email && <p className="text-[11px] font-bold text-red-500 mt-1">{errors.email}</p>}
            </div>

            {/* Alternate Phone */}
            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1.5">Alternate Contact Phone</label>
              <input
                type="tel"
                maxLength={10}
                value={formData.alternatePhone}
                onChange={(e) => setFormData({ ...formData, alternatePhone: e.target.value.replace(/\D/g, '') })}
                placeholder="Secondary phone"
                className="w-full px-4 py-2.5 bg-gray-50 font-mono border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-medium text-gray-900 focus:outline-none transition-all"
              />
            </div>

            {/* Date of Birth */}
            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1.5">Date of Birth</label>
              <input
                type="date"
                value={formData.dateOfBirth}
                onChange={(e) => setFormData({ ...formData, dateOfBirth: e.target.value })}
                className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-medium text-gray-900 focus:outline-none transition-all cursor-pointer"
              />
            </div>

            {/* Admission Date */}
            <div>
              <label className="block text-xs font-bold text-gray-700 mb-1.5">Admission Date</label>
              <input
                type="date"
                value={formData.admissionDate}
                onChange={(e) => setFormData({ ...formData, admissionDate: e.target.value })}
                className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-medium text-gray-900 focus:outline-none transition-all cursor-pointer"
              />
            </div>

            {/* Previous School */}
            <div className="sm:col-span-2">
              <label className="block text-xs font-bold text-gray-700 mb-1.5">Previous School Name</label>
              <input
                type="text"
                value={formData.previousSchool}
                onChange={(e) => setFormData({ ...formData, previousSchool: e.target.value })}
                placeholder="Name of previous educational institution, if any"
                className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-medium text-gray-900 focus:outline-none transition-all"
              />
            </div>

            {/* Residential Address */}
            <div className="sm:col-span-2">
              <label className="block text-xs font-bold text-gray-700 mb-1.5">Residential Address</label>
              <textarea
                rows={2}
                value={formData.address}
                onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                placeholder="Full residential address"
                className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 focus:border-[#001c46] rounded-xl text-xs font-medium text-gray-900 focus:outline-none transition-all resize-none"
              />
            </div>
          </div>
        </div>

        {/* Buttons */}
        <div className="flex items-center justify-end gap-3 pt-4 border-t border-gray-100">
          <button
            type="button"
            onClick={onCancel}
            disabled={isLoading}
            className="px-5 py-2.5 rounded-xl border border-gray-300 text-xs font-extrabold text-gray-700 hover:bg-gray-50 transition-colors cursor-pointer"
          >
            Cancel
          </button>

          <button
            type="submit"
            disabled={isLoading}
            className="px-6 py-2.5 rounded-xl bg-[#001c46] hover:bg-[#1a325d] text-white text-xs font-extrabold shadow-md hover:shadow-lg transition-all disabled:opacity-50 cursor-pointer flex items-center gap-2"
          >
            <Save className="w-4 h-4 text-[#FFC907]" />
            <span>{isLoading ? 'Saving...' : isEditMode ? 'Update Student' : 'Save Student'}</span>
          </button>
        </div>
      </form>
    </div>
  );
}
